views_get_user_geos.py:2:0: C0301: Line too long (110/100) (line-too-long)
views_get_user_geos.py:9:0: C0301: Line too long (103/100) (line-too-long)
views_get_user_geos.py:35:0: C0301: Line too long (118/100) (line-too-long)
views_get_user_geos.py:36:0: C0301: Line too long (107/100) (line-too-long)
views_get_user_geos.py:50:0: C0301: Line too long (120/100) (line-too-long)
views_get_user_geos.py:57:0: C0301: Line too long (104/100) (line-too-long)
views_get_user_geos.py:64:0: C0301: Line too long (108/100) (line-too-long)
views_get_user_geos.py:74:0: C0301: Line too long (117/100) (line-too-long)
views_get_user_geos.py:7:0: E0401: Unable to import 'common.apiauthentication.api.authenticateapi.views_authenticateapi' (import-error)
views_get_user_geos.py:8:0: E0401: Unable to import 'common.sessionmanagement.api.sessioncontrol.views_sessioncontrol' (import-error)
views_get_user_geos.py:9:0: E0401: Unable to import 'common.location.specificlib.views_lib' (import-error)
views_get_user_geos.py:12:0: C0103: Constant name "logger" doesn't conform to UPPER_CASE naming style (invalid-name)
views_get_user_geos.py:72:15: W0703: Catching too general exception Exception (broad-except)
views_get_user_geos.py:32:4: R0201: Method could be a function (no-self-use)

validations_get_user_geos.py:5:0: C0301: Line too long (117/100) (line-too-long)